name: logml
channels:
  - defaults
  - conda-forge
  - saravji
dependencies:
  - ipykernel=5.3.4
  - ipython=7.21.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter=1.0.0
  - pandas=1.2.2
  - scikit-learn=0.24.1
  - scipy=1.6.1
  - statsmodels=0.12.2
  - pandas-profiling=2.9.0
  - matplotlib=3.3.4
  - numpy=1.19.2
  - python=3.7.9
  - seaborn=0.11.1
  - lightgbm=3.1.1
  - tqdm=4.56.0
  - pyarrow=3.0.0
  - shapely=1.7.1
  - eli5=0.11.0
  - fbprophet=0.7.1
  - easydict=1.9
  - xlwt=1.3.0
  - autopep8=1.5.5
  - pytest=6.2.2
  - pip=21.0.1
  - papermill==2.3.1
  - pip:
      - sweetviz==2.0.9
      - nbconvert==5.6.1
      - boruta==0.3
      - pylint==2.7.2
      - click==7.1.2
      - hyperopt==0.2.5
      - shap==0.38.1
